version: 2.1

jobs:
  test_build:
    docker:
    - image: circleci/node:current
    steps:
      - checkout
      - run:
          name: NPM Install Frontend
          command: |
            npm install --save
      - run:
          name: NPM Install Backend
          command: |
            cd server && npm install --save && cd ..
      - run:
          name: Run Unit Tests
          command: |
            npm run test
      - run:
          name: Build
          command: |
            npm run build
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  test_build:
    jobs:
      - test_build
