version: 2.1

jobs:
  frontend-core:
    working_directory: ~/nixodeWebsite
    docker:
    - image: circleci/node:current
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: NPM CI
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Unit Tests
          command: npm run test:ci
      - run:
          name: Build
          command: npm run build:ci
      - store_test_results:
          path: ~/nixodeWebsite/coverage
      - store_artifacts:
          path: ~/nixodeWebsite/coverage
  backend-core:
    working_directory: ~/nixodeWebsite/server
    docker:
    - image: circleci/node:current
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: NPM CI
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: NPM Install
          command: cd server && npm install --save && cd ..
      - run:
          name: Build
          command: npm run build:ci
workflows:
  main:
    jobs:
      - frontend-core
      - backend-core
