version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  test_build:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: npm
      - build:
          steps:
            - run: npm run build

