version: 2.1

jobs:
  core:
    working_directory: ~/nixodeWebsite
    docker:
    - image: circleci/node:current
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: NPM CI Frontend
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: CD into Backend
          command: cd ~/nixodeWebsite/server
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: CD into Frontend
          command: cd ~/nixodeWebsite
      - run:
          name: Run Unit Tests
          command: npm run test:ci
      - run:
          name: Build
          command: npm run build
      - store_test_results:
          path: ~/nixodeWebsite/coverage
      - store_artifacts:
          path: ~/nixodeWebsite/coverage

workflows:
  main:
    jobs:
      - core
